### ISSUE TITLE
If the bus is placed first and then the cables are placed, they will not connect

### ISSUE THREAD

**Issue by lostmyself8** [alec016/modular-machinery-reborn#11] opened 2024-12-02 10:25 UTC
In 'Modular Machinery Reborn Energistics', place the bus first and then the cable, they will not be connected.

But if operated in reverse, it will connect.

**Comment by alec016** [comment] 2024-12-02 13:21
i will try to fix that for the next update, for the moment, rotating the block with the ae2 wrench should work and connect with the cable again(or first time) when it is in the correct position

**Comment by lostmyself8** [comment] 2024-12-03 09:22
Using a wrench is indeed useful, thank you very much.

**Comment by lostmyself8** [comment] 2024-12-03 09:31
By the way, after updating to 1.1.10, other blocks are not allowed to appear in the multi block structure. Is this normal?

For example, as shown in the picture, other blocks will prevent the formation of multiple blocks.But this won't happen in 1.1.9.
![2024-12-03_17 25 10](https://github.com/user-attachments/assets/4020b434-6a35-451b-ac79-e73ffa9de078)

**Comment by alec016** [comment] 2024-12-03 09:39
i will look into it, i probably changed something that breaks it

**Comment by alec016** [comment] 2024-12-03 10:12
i cant reproduce the issue. Can you share your machine to see if there is an issue with that?

**Comment by lostmyself8** [comment] 2024-12-03 12:34
> 我无法重现这个问题。您能否共享您的机器以查看是否有问题？

sure.

I used kubejs to write it, and I used blocks from the [Immersive Engineering](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering). You may need to add it.

[huge_coke_oven.json](https://github.com/user-attachments/files/17992885/huge_coke_oven.json)

It seems that sending files with a .js extension is not supported here, so I changed it to. json.

**Comment by alec016** [comment] 2024-12-03 14:32
One thing, the "#modular_machinery_reborn:all_casing" already contains every single bus/hatch/casing from mmr and all its addons, so using 3 additional ones for other blocks that already contains its a bit unnecesary. Defining twice the same key can produce an error on the check of the structure or parsing it.
```js
.keys(
            {
                "a": "minecraft:coal_block",
                "b": "minecraft:bricks",
                "c": "immersiveengineering:cokebrick",
                "p": ["#modular_machinery_reborn:all_casing" ]
            }
        )
```
In any case, in the next update will be fixed

**Comment by lostmyself8** [comment] 2024-12-04 04:02
Oh. Thank you for the reminder

**Closed as completed** 2024-12-04 23:46 UTC
